"""add document structures and key information

Revision ID: 162529bf34d0
Revises: 122251925aca
Create Date: 2026-08-07 10:29:03.324943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '162529bf34d0'
down_revision: Union[str, Sequence[str], None] = '122251925aca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_structures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processing_run_id', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.String(length=50), nullable=False),
    sa.Column('structure_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('element_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('element_count >= 0', name='ck_document_structures_element_count_nonnegative'),
    sa.ForeignKeyConstraint(['processing_run_id'], ['processing_runs.id'], name='fk_document_structures_processing_run_id_processing_runs', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_structures_content_hash'), 'document_structures', ['content_hash'], unique=False)
    op.create_index(op.f('ix_document_structures_processing_run_id'), 'document_structures', ['processing_run_id'], unique=True)
    op.create_table('key_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('source_processing_run_id', sa.Integer(), nullable=True),
    sa.Column('application_period', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('eligibility', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('supply_information', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('income_asset_criteria', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('required_documents', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('winner_announcement', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('contact_information', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('extraction_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("extraction_status IN ('pending', 'completed', 'failed')", name='ck_key_information_extraction_status'),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], name='fk_key_information_announcement_id_announcements', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_processing_run_id'], ['processing_runs.id'], name='fk_key_information_source_processing_run_id_processing_runs', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_key_information_announcement_id'), 'key_information', ['announcement_id'], unique=True)
    op.create_index(op.f('ix_key_information_extraction_status'), 'key_information', ['extraction_status'], unique=False)
    op.create_index(op.f('ix_key_information_source_processing_run_id'), 'key_information', ['source_processing_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_key_information_source_processing_run_id'), table_name='key_information')
    op.drop_index(op.f('ix_key_information_extraction_status'), table_name='key_information')
    op.drop_index(op.f('ix_key_information_announcement_id'), table_name='key_information')
    op.drop_table('key_information')
    op.drop_index(op.f('ix_document_structures_processing_run_id'), table_name='document_structures')
    op.drop_index(op.f('ix_document_structures_content_hash'), table_name='document_structures')
    op.drop_table('document_structures')
    # ### end Alembic commands ###
