"""add chunk and embedding schema

Revision ID: 9672336f0911
Revises: de0623e9f6cc
Create Date: 2026-08-06 16:36:32.728334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '9672336f0911'
down_revision: Union[str, Sequence[str], None] = 'de0623e9f6cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunk_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processing_run_id', sa.Integer(), nullable=False),
    sa.Column('chunker_version', sa.String(length=50), nullable=False),
    sa.Column('strategy', sa.String(length=100), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('input_content_version', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('chunk_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(NOT is_active) OR status = 'completed'", name='ck_chunk_sets_active_requires_completed'),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed')", name='ck_chunk_sets_status'),
    sa.CheckConstraint('chunk_count >= 0', name='ck_chunk_sets_chunk_count_nonnegative'),
    sa.ForeignKeyConstraint(['processing_run_id'], ['processing_runs.id'], name='fk_chunk_sets_processing_run_id_processing_runs', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunk_sets_processing_run_id'), 'chunk_sets', ['processing_run_id'], unique=False)
    op.create_index(op.f('ix_chunk_sets_status'), 'chunk_sets', ['status'], unique=False)
    op.create_index('uq_chunk_sets_one_active_per_processing_run', 'chunk_sets', ['processing_run_id'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_table('chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chunk_set_id', sa.Integer(), nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('external_chunk_key', sa.String(length=512), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('document_format', sa.String(length=10), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('section_path', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('search_text', sa.Text(), nullable=True),
    sa.Column('embedding_text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('character_count', sa.Integer(), nullable=True),
    sa.Column('source_block_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('source_table_id', sa.String(length=255), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_reference', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='completed', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("document_format IN ('hwp', 'hwpx')", name='ck_chunks_document_format'),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed', 'skipped')", name='ck_chunks_status'),
    sa.CheckConstraint('(token_count IS NULL OR token_count >= 0) AND (character_count IS NULL OR character_count >= 0)', name='ck_chunks_counts_nonnegative'),
    sa.CheckConstraint('source_page IS NULL OR source_page >= 1', name='ck_chunks_source_page_positive'),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], name='fk_chunks_announcement_id_announcements', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chunk_set_id'], ['chunk_sets.id'], name='fk_chunks_chunk_set_id_chunk_sets', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='fk_chunks_document_id_documents', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_set_id', 'chunk_index', name='uq_chunks_set_index'),
    sa.UniqueConstraint('chunk_set_id', 'external_chunk_key', name='uq_chunks_set_external_key')
    )
    op.create_index(op.f('ix_chunks_announcement_id'), 'chunks', ['announcement_id'], unique=False)
    op.create_index(op.f('ix_chunks_chunk_set_id'), 'chunks', ['chunk_set_id'], unique=False)
    op.create_index(op.f('ix_chunks_content_hash'), 'chunks', ['content_hash'], unique=False)
    op.create_index(op.f('ix_chunks_content_type'), 'chunks', ['content_type'], unique=False)
    op.create_index(op.f('ix_chunks_document_format'), 'chunks', ['document_format'], unique=False)
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_chunks_status'), 'chunks', ['status'], unique=False)
    op.create_table('embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('model_version', sa.String(length=100), server_default='default', nullable=False),
    sa.Column('dimension', sa.Integer(), server_default='1024', nullable=False),
    sa.Column('normalized', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('embedding_text_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding', Vector(1024), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status <> 'completed' OR embedding IS NOT NULL", name='ck_embeddings_completed_requires_vector'),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed')", name='ck_embeddings_status'),
    sa.CheckConstraint('dimension = 1024', name='ck_embeddings_dimension'),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], name='fk_embeddings_chunk_id_chunks', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id', 'model_name', 'model_version', name='uq_embeddings_chunk_model_version')
    )
    op.create_index(op.f('ix_embeddings_chunk_id'), 'embeddings', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_embeddings_model_name'), 'embeddings', ['model_name'], unique=False)
    op.create_index(op.f('ix_embeddings_status'), 'embeddings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_embeddings_status'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_model_name'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_chunk_id'), table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index(op.f('ix_chunks_status'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_document_format'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_content_type'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_content_hash'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_chunk_set_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_announcement_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('uq_chunk_sets_one_active_per_processing_run', table_name='chunk_sets', postgresql_where=sa.text('is_active'))
    op.drop_index(op.f('ix_chunk_sets_status'), table_name='chunk_sets')
    op.drop_index(op.f('ix_chunk_sets_processing_run_id'), table_name='chunk_sets')
    op.drop_table('chunk_sets')
    # ### end Alembic commands ###
