"""add admin and error log tables

Revision ID: b328bf2c4b4e
Revises: 162529bf34d0
Create Date: 2026-08-07 15:08:38.697461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b328bf2c4b4e'
down_revision: Union[str, Sequence[str], None] = '162529bf34d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login_id', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=30), server_default='admin', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login_id')
    )
    op.create_table('error_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_run_id', sa.Integer(), nullable=True),
    sa.Column('announcement_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('processing_run_id', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(length=30), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='unresolved', nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("error_type IN ('collection', 'download', 'parsing', 'normalizing', 'structuring', 'verification', 'chunking', 'embedding', 'database', 'rag', 'llm')", name='ck_error_logs_error_type'),
    sa.CheckConstraint("status IN ('unresolved', 'in_progress', 'resolved')", name='ck_error_logs_status'),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], name='fk_error_logs_announcement_id_announcements', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['collection_run_id'], ['collection_runs.id'], name='fk_error_logs_collection_run_id_collection_runs', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='fk_error_logs_document_id_documents', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['processing_run_id'], ['processing_runs.id'], name='fk_error_logs_processing_run_id_processing_runs', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_logs_announcement_id'), 'error_logs', ['announcement_id'], unique=False)
    op.create_index(op.f('ix_error_logs_collection_run_id'), 'error_logs', ['collection_run_id'], unique=False)
    op.create_index(op.f('ix_error_logs_created_at'), 'error_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_error_logs_document_id'), 'error_logs', ['document_id'], unique=False)
    op.create_index(op.f('ix_error_logs_error_type'), 'error_logs', ['error_type'], unique=False)
    op.create_index(op.f('ix_error_logs_processing_run_id'), 'error_logs', ['processing_run_id'], unique=False)
    op.create_index(op.f('ix_error_logs_stage'), 'error_logs', ['stage'], unique=False)
    op.create_index(op.f('ix_error_logs_status'), 'error_logs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_error_logs_status'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_stage'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_processing_run_id'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_error_type'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_document_id'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_created_at'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_collection_run_id'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_announcement_id'), table_name='error_logs')
    op.drop_table('error_logs')
    op.drop_table('admins')
    # ### end Alembic commands ###
