"""add processing runs and artifacts

Revision ID: de0623e9f6cc
Revises: 7450a47c33a3
Create Date: 2026-08-06 16:03:01.734609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de0623e9f6cc'
down_revision: Union[str, Sequence[str], None] = '7450a47c33a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('execution_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('verification_status', sa.String(length=20), server_default='not_run', nullable=False),
    sa.Column('current_stage', sa.String(length=30), nullable=True),
    sa.Column('pipeline_version', sa.String(length=50), nullable=True),
    sa.Column('output_root_path', sa.Text(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('error_stage', sa.String(length=30), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('parser_warning_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('normalizer_warning_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('verification_error_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('verification_warning_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("execution_status IN ('pending', 'running', 'succeeded', 'failed')", name='ck_processing_runs_execution_status'),
    sa.CheckConstraint("verification_status IN ('not_run', 'pending', 'pass', 'warning', 'fail')", name='ck_processing_runs_verification_status'),
    sa.CheckConstraint('parser_warning_count >= 0 AND normalizer_warning_count >= 0 AND verification_error_count >= 0 AND verification_warning_count >= 0', name='ck_processing_runs_counts_nonnegative'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='fk_processing_runs_document_id_documents', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_runs_document_id'), 'processing_runs', ['document_id'], unique=False)
    op.create_index(op.f('ix_processing_runs_execution_status'), 'processing_runs', ['execution_status'], unique=False)
    op.create_index(op.f('ix_processing_runs_verification_status'), 'processing_runs', ['verification_status'], unique=False)
    op.create_table('processing_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processing_run_id', sa.Integer(), nullable=False),
    sa.Column('artifact_type', sa.String(length=20), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('schema_version', sa.String(length=30), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("artifact_type IN ('parsed', 'normalized', 'structured', 'verification', 'log')", name='ck_processing_artifacts_type'),
    sa.CheckConstraint('file_size_bytes >= 0', name='ck_processing_artifacts_file_size_nonnegative'),
    sa.ForeignKeyConstraint(['processing_run_id'], ['processing_runs.id'], name='fk_processing_artifacts_run_id_processing_runs', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('processing_run_id', 'artifact_type', name='uq_processing_artifacts_run_type')
    )
    op.create_index(op.f('ix_processing_artifacts_artifact_type'), 'processing_artifacts', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_processing_artifacts_processing_run_id'), 'processing_artifacts', ['processing_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_artifacts_processing_run_id'), table_name='processing_artifacts')
    op.drop_index(op.f('ix_processing_artifacts_artifact_type'), table_name='processing_artifacts')
    op.drop_table('processing_artifacts')
    op.drop_index(op.f('ix_processing_runs_verification_status'), table_name='processing_runs')
    op.drop_index(op.f('ix_processing_runs_execution_status'), table_name='processing_runs')
    op.drop_index(op.f('ix_processing_runs_document_id'), table_name='processing_runs')
    op.drop_table('processing_runs')
    # ### end Alembic commands ###
